/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "newsfeed_constants.h"



const newsfeedConstants g_newsfeed_constants;

newsfeedConstants::newsfeedConstants() {
}



