/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef newsfeed_CONSTANTS_H
#define newsfeed_CONSTANTS_H

#include "newsfeed_types.h"



class newsfeedConstants {
 public:
  newsfeedConstants();

};

extern const newsfeedConstants g_newsfeed_constants;



#endif
